#!/bin/bash
set -e

swift --version

swift build -c release \
    --explicit-target-dependency-import-check=error \
    --build-tests

swift test -c release \
    --explicit-target-dependency-import-check=error \
    --skip-build
