name: benchmark

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Benchmark memory consumption
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build environment
                run: |
                    docker build -f Benchmarks/Memory/Dockerfile -t benchmark .

            -   name: Build test application
                run: |
                    docker run --rm -v=$PWD:/swift -w=/swift \
                        benchmark \
                        swift build -c release --product FirewallUsage

            -   name: Build firewall
                run: |
                    docker run --rm -v=$PWD:/swift -w=/swift \
                        -e IPINFO_TOKEN=${{ secrets.IPINFO_TOKEN }} \
                        benchmark \
                        Scripts/Package

            -   name: Run test application (200MB memory limit)
                run: |
                    docker run --rm -v=$PWD:/swift -w=/swift --memory 200m \
                        -e LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 \
                        benchmark \
                        .build/release/FirewallUsage

            -   name: Run test application (150MB memory limit)
                run: |
                    docker run --rm -v=$PWD:/swift -w=/swift --memory 150m \
                        -e LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 \
                        benchmark \
                        .build/release/FirewallUsage

            -   name: Run test application (100MB memory limit)
                run: |
                    docker run --rm -v=$PWD:/swift -w=/swift --memory 100m \
                        -e LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 \
                        benchmark \
                        .build/release/FirewallUsage

            -   name: Run test application (80MB memory limit)
                run: |
                    docker run --rm -v=$PWD:/swift -w=/swift --memory 80m \
                        -e LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 \
                        benchmark \
                        .build/release/FirewallUsage
