name: tests

on:
    workflow_dispatch:
    push:
        branches: [ master ]
        tags:
            -   '[0-9]+.[0-9]+.[0-9]+'
    pull_request:
        branches: [ master ]

jobs:
    changes:
        runs-on: ubuntu-latest
        name: Assess changes
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Decide checks 💖
                uses: tj-actions/changed-files@v47
                id: changes
                with:
                    files_ignore: |
                        README.md
                        LICENSE
                        NOTICE
                        .mailmap
                        .gitignore
                        .github/FUNDING.yml
        outputs:
            code_changed: ${{ steps.changes.outputs.any_changed }}

    macos:
        runs-on: macos-26
        name: macOS
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Select Xcode 26.3 💖
                run: sudo xcode-select -s /Applications/Xcode_26.3.app/Contents/Developer

            -   name: 💖 Format 💖
                run: |
                    swift package dollup --allow-writing-to-package-directory
                    git diff --exit-code

            -   name: 💖 Test 💖
                run: Scripts/TestAll

    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        steps:
            -   name: 💖 Install Swift 💖
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.2.4-release/ubuntu2404/swift-6.2.4-RELEASE"
                    swift-id: "swift-6.2.4-RELEASE-ubuntu24.04"

            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Format 💖
                run: |
                    swift package dollup --allow-writing-to-package-directory
                    git diff --exit-code

            -   name: 💖 Test 💖
                run: Scripts/TestAll

    linux-deploy:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04 (deploy)
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' && github.event_name != 'pull_request' }}
        steps:
            -   name: 💖 Setup AWS CLI 💖
                uses: aws-actions/configure-aws-credentials@v6
                with:
                    aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_SECRET }}
                    aws-access-key-id: ${{ vars.AWS_S3_ACCESS_KEY }}
                    aws-region: us-east-1

            -   name: 💖 Install Swift 💖
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.2.4-release/ubuntu2404/swift-6.2.4-RELEASE"
                    swift-id: "swift-6.2.4-RELEASE-ubuntu24.04"

            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Build prefabricator 💖
                run: |
                    swift build -c release \
                        --explicit-target-dependency-import-check=error \
                        --static-swift-stdlib \
                        --product swift-ip-prefabricator
                    cp .build/release/swift-ip-prefabricator .

            -   name: 💖 Build blocklist image 💖
                env:
                    IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
                run: Scripts/Update swift-ip-prefabricator

            -   name: 💖 Test blocklist image 💖
                run: swift run -c release FirewallUsage 98.223.208.128

            -   name: 💖 Deploy prefabricator 💖
                env:
                    APP: "swift-ip"
                    DEPLOY_VERSION: ${{ github.head_ref || github.ref_name }}
                run: |
                    gzip -kf9 swift-ip-prefabricator
                    aws s3 cp swift-ip-prefabricator.gz \
                        "s3://rarestype/public/${APP}/${DEPLOY_VERSION}/Linux-$(uname -m)/prefabricator.gz" \
                        --content-encoding gzip \
                        --content-type application/gzip
